import re

sents = {
 "4.1 controls re-judge": "It does not move the two controls in our favour either: of the nineteen verdicts the six re-judge files rewrite, fifteen move a case toward confirmation under the convention, four move between Confirmed and Human-Review, which the convention counts alike, and none moves away; the arms' true-positive sets are unchanged (48 and 33) while their false-positive counts rise by two and one---suppression 0.467 0.400 and 0.933 0.900---and on the forced reading the no-source arm's recall rises by one, to 31.",
 "4.1 Holm": "Read as a family of ten, a Holm correction leaves the four smallest significant---the bundled contrast on the second backbone (0.0001), that backbone's perspective contrast (0.0034), the bundled contrast on the primary backbone (0.0039) and the evidence-access contrast (0.0039), tested against /10, /9, /8 and /7---and stops at the fifth (0.0225), so the deployed stage's own recall-level advantage over the flat judge, and everything larger than it, should be read descriptively.",
 "RW Ma et al": "The closest work to ours is Ma et al. manyminds25, who measure multi-agent judging for bias rather than for accuracy and find that debate amplifies judge biases after an initial round while a meta-judge resists them; they establish that adding perspectives is not a uniform correction, which is the premise our four-perspective stage is built on and, on this pool, the finding we reproduce in a different currency: the organization changes which cases are decided, not how many, and on a second backbone it costs recall rather than buying it.",
 "4.4 nine arms": "Across the nine judging arms this section contrasts---the flat judge, flat+ schema, flat+ aggregation, full-no-aggregation, full stage and full-no-source on the primary backbone, and the second backbone's flat, flat+ aggregation and full---forced recall spans [23, 31] of 51 against a convention span of [27, 48]; the contract-only core, a blind baseline, reaches 8 forced and 8 convention, and the two source-only configurations 20 and 19 forced (36 and 37 convention, the two recall figures quoted below).",
 "4.5 C=Refuted classes": "The nineteen judgments this census closes by C=Refuted record what they rest on, and reading them separates three kinds of evidence rather than one: fifteen cite a comment or docstring in the implementation; two (milvus_026, in two of its three runs) cite the server's own name-validation rule, whose code and error message those runs name; and two (milvus_011 and milvus_012, each in its third run) rest on code structure---a default expression, a fallback chain.",
 "4.5 weaker kind": "But the last two are the weaker kind, and the same two cases show why the distinction is not academic: in both, the case's other runs recorded a weak refutation and gave their reason---milvus_011's second run notes that a silent behaviour has no comment behind it, and milvus_012's second run states that the fallback-chain structure shows design but carries no comment or quote, so the red line governing this perspective does not admit it.",
 "3.5 aggregation": "Aggregation is fixed, and the order in which its clauses are tried is part of the design: a contract confirmation decides the case; a contract refutation with the objective-constraint perspective confirmed routes rather than closing; otherwise a contract refutation closes to False-Positive; an objective-constraint confirmation decides a contract-neutral case; a cognition hit on either side decides a case the earlier clauses left open; an explicit by-design refutation closes; and everything else routes to human review.",
}
for k, s in sents.items():
    toks = [t for t in re.split(r"\s+", s) if t and t != "---"]
    print(f"{len(toks):3d} words (dashes not counted)  {k}")
