#!/usr/bin/env python3
"""
Material Passport — hash 验证脚本
验证 structured_contract.json 的 _passport.contract_hash 完整性。

用法:
  python scripts/passport_verify.py <path/to/structured_contract.json>

退出码:
  0 = PASS (hash 匹配)
  1 = NO_PASSPORT (无 _passport 字段，旧格式)
  2 = TAMPERED (hash 不匹配，可能被篡改)
  3 = INVALID_JSON (文件无法解析)
"""

import json
import hashlib
import sys
import os
from datetime import datetime, timezone


def compute_hash(data: dict, algorithm: str = "sha256") -> str:
    """计算排除 _passport 字段后的契约 hash"""
    data_without_passport = {k: v for k, v in data.items() if k != "_passport"}
    canonical_json = json.dumps(data_without_passport, sort_keys=True, separators=(",", ":"))
    h = hashlib.new(algorithm)
    h.update(canonical_json.encode("utf-8"))
    return f"{algorithm}:{h.hexdigest()}"


def verify_passport(contract_path: str) -> dict:
    """验证 Material Passport，返回结果字典"""
    result = {
        "file": contract_path,
        "status": "UNKNOWN",
        "checked_at": datetime.now(timezone.utc).isoformat(),
        "details": {}
    }

    if not os.path.exists(contract_path):
        result["status"] = "FILE_NOT_FOUND"
        result["details"]["error"] = f"File not found: {contract_path}"
        return result

    try:
        with open(contract_path, "r", encoding="utf-8") as f:
            contract = json.load(f)
    except json.JSONDecodeError as e:
        result["status"] = "INVALID_JSON"
        result["details"]["error"] = str(e)
        return result

    passport = contract.get("_passport")
    if not passport:
        result["status"] = "NO_PASSPORT"
        result["details"]["warning"] = (
            "No _passport field found. This contract was generated by an older version "
            "of TestVDB (pre-v2.0). Hash verification skipped."
        )
        return result

    expected_hash = passport.get("contract_hash")
    algorithm = passport.get("contract_hash_algorithm", "sha256")

    if not expected_hash:
        result["status"] = "NO_HASH"
        result["details"]["error"] = "_passport exists but contract_hash is missing"
        return result

    try:
        actual_hash = compute_hash(contract, algorithm)
    except ValueError:
        result["status"] = "UNSUPPORTED_ALGORITHM"
        result["details"]["error"] = f"Unsupported hash algorithm: {algorithm}"
        return result

    result["details"]["expected_hash"] = expected_hash
    result["details"]["actual_hash"] = actual_hash
    result["details"]["algorithm"] = algorithm
    result["details"]["schema_version"] = passport.get("schema_version", "unknown")
    result["details"]["generated_at"] = passport.get("generation", {}).get("generated_at", "unknown")

    # ponytail: 归一化前缀（compute_hash 返回 "sha256:hex"，passport 存裸 hex）；canonical = 裸 hexdigest
    if actual_hash.split(":", 1)[-1] == expected_hash.split(":", 1)[-1]:
        result["status"] = "PASS"
    else:
        result["status"] = "TAMPERED"
        result["details"]["error"] = (
            f"Hash mismatch! Contract content has been modified since generation. "
            f"Expected: {expected_hash[:32]}..., Actual: {actual_hash[:32]}..."
        )

    return result


def _self_check() -> int:
    """Self-check: compute_hash 纯函数 + --compute-hash CLI 子命令.

    覆盖 test_b_side_gates.py 没测的 gap：
    - compute_hash 排除 _passport（含/不含应同 hash）+ sort_keys 稳定性 + hash 格式
    - --compute-hash CLI 子命令（contract-formalizer.md L456 承诺 generator 调用，
      原本未实现 — 本次补上 + self-check 守住接口契约）
    """
    import tempfile
    import subprocess
    failures = []

    def expect(cond, msg):
        if not cond:
            failures.append(msg)

    # compute_hash 排除 _passport 字段
    base = {"target": "qdrant", "version": "1.13.0", "endpoints": []}
    with_passport = dict(base)
    with_passport["_passport"] = {"contract_hash": "precomputed", "schema_version": "2.0"}
    expect(compute_hash(base) == compute_hash(with_passport),
           "compute_hash 应排除 _passport 字段（含/不含应同 hash）")

    # canonical_json sort_keys 稳定性（key 顺序无关）
    expect(compute_hash({"b": 1, "a": 2}) == compute_hash({"a": 2, "b": 1}),
           "compute_hash 应 sort_keys（key 顺序无关应同 hash）")

    # hash 格式（sha256: + 64 hex）
    h = compute_hash(base)
    expect(h.startswith("sha256:"), f"hash 应 sha256: 前缀, got {h}")
    expect(len(h.split(":")[1]) == 64,
           f"sha256 hex 应 64 字符, got {len(h.split(':')[1])}")

    # --compute-hash CLI 子命令（contract-formalizer.md L456 承诺的接口）
    with tempfile.TemporaryDirectory() as td:
        p = os.path.join(td, "contract.json")
        with open(p, "w", encoding="utf-8") as f:
            json.dump(base, f)
        r = subprocess.run(
            [sys.executable, os.path.abspath(__file__), "--compute-hash", p],
            capture_output=True, text=True, timeout=10,
        )
        expect(r.returncode == 0,
               f"--compute-hash 应 exit 0, got {r.returncode}, stderr={r.stderr}")
        expect(r.stdout.strip() == compute_hash(base),
               f"--compute-hash 输出应 == compute_hash(), got {r.stdout.strip()!r}")

        # 不存在文件 → exit 3
        r2 = subprocess.run(
            [sys.executable, os.path.abspath(__file__), "--compute-hash",
             os.path.join(td, "nope.json")],
            capture_output=True, text=True, timeout=10,
        )
        expect(r2.returncode == 3,
               f"--compute-hash 不存在文件应 exit 3, got {r2.returncode}")

    if failures:
        print("self-check FAIL:", file=sys.stderr)
        for m in failures:
            print(f"  - {m}", file=sys.stderr)
        return 1
    print("self-check OK")
    return 0


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "--self-check":
        sys.exit(_self_check())
    if len(sys.argv) >= 3 and sys.argv[1] == "--compute-hash":
        # contract-formalizer.md L456 承诺的接口：输出 hash 字符串供 generator 填入 _passport.contract_hash
        contract_path = sys.argv[2]
        try:
            with open(contract_path, "r", encoding="utf-8") as f:
                contract = json.load(f)
        except (json.JSONDecodeError, FileNotFoundError) as e:
            print(f"ERROR: {e}", file=sys.stderr)
            sys.exit(3)
        print(compute_hash(contract))
        sys.exit(0)
    if len(sys.argv) < 2:
        print("Usage: python scripts/passport_verify.py <path/to/structured_contract.json>")
        print("       python scripts/passport_verify.py --compute-hash <path>")
        print("       python scripts/passport_verify.py --self-check")
        sys.exit(3)

    contract_path = sys.argv[1]
    result = verify_passport(contract_path)
    print(json.dumps(result, indent=2, ensure_ascii=False))

    status_map = {"PASS": 0, "NO_PASSPORT": 1, "TAMPERED": 2,
                  "INVALID_JSON": 3, "FILE_NOT_FOUND": 3, "NO_HASH": 2}
    sys.exit(status_map.get(result["status"], 3))


if __name__ == "__main__":
    main()
